server:
  port: 8001
  servlet:
    context-path: /douyin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo

spring:
  application:
    name: provider-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.105:3306/douyin4j?serverTimezone=Asia/Shanghai
      username: root
      password: 123123
  redis:
    database: 0
    host: 192.168.2.105
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
