spring:
  profiles:
    active: dev


---
server:
  port: 7002

spring:
  profiles: dev
  application:
    name: eureka-config

eureka:
  instance:
    hostname: eureka7002.com               #Eureka服务器实例名称
  client:
    register-with-eureka: false       #是否向服务器注册自己
    fetch-registry: false             #false表示自己是注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka   #配置url

---
server:
  port: 7005

spring:
  profiles: test
  application:
    name: eureka-config

eureka:
  instance:
    hostname: eureka7002.com               #Eureka服务器实例名称
  client:
    register-with-eureka: false       #是否向服务器注册自己
    fetch-registry: false             #false表示自己是注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka   #配置url