server:
  port: 6060

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/juityvan/douyin4j-config.git
          username: juityvan
          password: Aa13205763766
        default-label: master

