spring:
  application:
    name: zuul-gateway
  servlet:
    multipart:
      max-file-size: 104857600      #100Mb
      max-request-size: 104857600   #100Mb

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

zuul:
  routes:
    user:
      path: /douyin/user/**
      url: http://192.168.2.104:8001/
      strip-prefix: false
    follow:
      path: /douyin/relation/**
      url: http://192.168.2.104:9001/
      strip-prefix: false
    favorite:
      path: /douyin/favorite/**
      url: http://192.168.2.104:5001/
      strip-prefix: false
    comment:
      path: /douyin/comment/**
      url: http://192.168.2.104:4001/
      strip-prefix: false
    video:
      path: /douyin/publish/**
      url: http://192.168.2.104:6001/
      strip-prefix: false
    videoFeed:
      path: /douyin/feed/**
      url: http://192.168.2.104:6001/
      strip-prefix: false
    videoPlay:
      path: /douyin/static/**
      url: http://192.168.2.104:6001/
      strip-prefix: false
